FROM quay.io/fedora-ostree-desktops/silverblue:41

# Create user "maik"
RUN useradd -G wheel -u 1000 -s /bin/bash maik && \
  usermod -p '$6$yIc8YCsXt1rkzeoc$72vBqymGWj7MCX0GduTvUMBqxAvxz4WYDJcASMEBaevyCrKAI1btoDM5czg366gwr6N55Zrn5zlPKTaUGsprV/' maik

# Apply file-based customization
COPY \_shared/files/ files/ /

# Enable system services
RUN systemctl enable bootc-fetch-apply-updates.timer

# Remove unneeded packages
RUN dnf remove -y                                                                                       \
  firefox                                                                                               \
  firefox-langpacks                                                                                     \
  gnome-system-monitor                                                                                  \
&& /usr/libexec/containerbuild/cleanup.sh

# Add rpmfusion
RUN dnf install -y                                                                                      \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm       \
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
&& /usr/libexec/containerbuild/cleanup.sh

# Add addtional codecs
RUN dnf swap -y ffmpeg-free ffmpeg --allowerasing                                                       \
  && dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld                                              \
  && dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld                                        \
&& /usr/libexec/containerbuild/cleanup.sh

# Add language pack
RUN dnf install -y                                                                                     \
  langpacks-de                                                                                         \
&& /usr/libexec/containerbuild/cleanup.sh

# Add fonts
RUN dnf install -y                                                                                     \
  rsms-inter-fonts                                                                                     \
  jetbrains-mono-fonts                                                                                 \
&& /usr/libexec/containerbuild/cleanup.sh

# Add syncthing
RUN dnf install -y                                                                                     \
  syncthing                                                                                            \
&& /usr/libexec/containerbuild/cleanup.sh

# Add basic gnome appllications
RUN dnf install -y                                                                                     \
  gnome-shell-extension-gsconnect                                                                      \
  simple-scan                                                                                          \
&& /usr/libexec/containerbuild/cleanup.sh

# Hide some application entries
RUN for i in                                                                                           \
  /usr/share/applications/syncthing-start.desktop                                                      \
  /usr/share/applications/syncthing-ui.desktop                                                         \
; do sed -i 's@\[Desktop Entry\]@\[Desktop Entry\]\nNoDisplay=true@g' $i; done
