---
name: build-pluto
on:
    push:
        branches:
            - main
        paths-ignore:
            - '**/README.md'
            - 'juno/*'
    schedule:
     - cron: '05 10 * * *'  # 10:05am UTC everyday
    workflow_dispatch:

jobs:
  build_pluto:
    name: Build and push image
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: "pluto"
      base_image_name: "kinoite"
