---
name: build-juno
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "charon/**"
      - ".github/workflows/build-charon.yml"
      - "pluto/**"
      - ".github/workflows/build-pluto.yml"
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  workflow_dispatch:

jobs:
  build_juno:
    name: Build and push image
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: "juno"
      base_image_name: "silverblue"
    secrets: inherit
