---
name: scan-pluto
on:
  schedule:
    - cron: "0 * * * *"   # at minute 0 of every hour
  workflow_dispatch:

jobs:
  scan-pluto:
    runs-on: ubuntu-latest
    steps:
    - name: Scan container for vulnerabilities using DNF
      run: |
        docker run --rm ghcr.io/michaelmnemonic/pluto:latest bash -c '
          dnf updateinfo summary
        ' > scan_result || true

    - name: Rebuild image if vulnerabilities is found
      run: |
        if grep -q "Security    : 0" scan_result; then
          echo "No Security issues found!"
        else
          echo "Security issues found!"
          gh workflow run build-pluto.yml
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
