---
name: scan-pluto
on:
  schedule:
    - cron: "0 * * * *"   # at minute 0 of every hour
    - cron: "30 * * * *"  # at minute 30 of every hour
  workflow_dispatch:

jobs:
  scan-pluto:
    runs-on: ubuntu-latest
    container: ghcr.io/michaelmnemonic/pluto:latest
    steps:
    - name: Scan container for vulnerabilities using DNF
      run: |
        dnf updateinfo list --security
