---
name: scan-pluto
on:
  schedule:
    - cron: "0 * * * *"   # at minute 0 of every hour
  workflow_dispatch:

jobs:
  scan-pluto:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Scan container for vulnerabilities using DNF
      run: |
        echo "Security    : 1" >> scan_result

    - name: Rebuild image if vulnerabilities is found
      run: |
        if grep -q "Security    : 0" scan_result; then
          echo "No Security issues found!"
        else
          echo "Security issues found!"
          gh workflow run build-pluto.yml
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
